code: 131229
gijiroku: data/gijiroku.csv
giin: data/giin.csv
iinkai: data/iinkai.csv
years: data/years.csv
jogai: data/exclusion.csv
font: static/ShipporiMinchoB1-ExtraBold.ttf
target:
  place: 葛飾区
  start: 1996年2月
  end: 2022年11月
  url: https://www.kensakusystem.jp/katsushika/sapphire.html
developer:
  name: 岡村健一
  contact: https://twitter.com/Okamura_Kenichi
  img: static/developer.png